version: "1"
services:
  frontend-server:
    image: frontend-server
    build: ./client/
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - mern-app

  backend-server:
    image: backend-server
    build: ./server/
    ports:
      - "3001:3001"
    networks:
      - mern-app

  mongo:
    image: mongo:4.4-bionic
    ports:
      - "271017:271017"
    networks:
      - mern-app

    volumes:
      - mongo-data:/data/db

  networks:
    mern-app:
      driver: bridge

  volumes:
    mongo-data:
      driver: local
